// Login
export const LOGIN_ENABLE_LOADER = 'LOGIN_ENABLE_LOADER';

export const LOGIN_DISABLE_LOADER = 'LOGIN_DISABLE_LOADER';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';

export const LOGIN_RESPONSE = 'LOGIN_RESPONSE';

export const LOGIN_FAILED = 'LOGIN_FAILED';

export const LOG_OUT = 'LOG_OUT';

// SignUp
export const SIGNUP_ENABLE_LOADER = 'SIGNUP_ENABLE_LOADER';

export const SIGNUP_DISABLE_LOADER = 'SIGNUP_DISABLE_LOADER';

export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';

export const SIGNUP_RESPONSE = 'SIGNUP_RESPONSE';

export const SIGNUP_LOADING_ENDED = 'SIGNUP_LOADING_ENDED';

export const SIGNUP_FAILED = 'SIGNUP_FAILED';

// forgot password

export const FORGOT_PASSWORD_ENABLE_LOADER = 'FORGOT_PASSWORD_ENABLE_LOADER';

export const FORGOT_PASSWORD_DISABLE_LOADER = 'FORGOT_PASSWORD_DISABLE_LOADER';

export const FORGOT_PASSWORD_REQUEST = 'FORGOT_PASSWORD_REQUEST';

export const FORGOT_PASSWORD_RESPONSE = 'FORGOT_PASSWORD_RESPONSE';

export const FORGOT_PASSWORD_LOADING_ENDED = 'FORGOT_PASSWORD_LOADING_ENDED';

export const FORGOT_PASSWORD_FAILED = 'FORGOT_PASSWORD_FAILED';

export const REQUEST_OTP = 'REQUEST_OTP';
export const REQUEST_OTP_FAILED = 'REQUEST_OTP_FAILED';
export const REQUEST_OTP_RESPONSE = 'REQUEST_OTP_RESPONSE';

export const REQUEST_PASSWORD_RESET = 'REQUEST_PASSWORD_RESET';
export const REQUEST_PASSWORD_RESET_FAILED = 'REQUEST_PASSWORD_RESET_FAILED';
export const REQUEST_PASSWORD_RESET_RESPONSE =
  'REQUEST_PASSWORD_RESET_RESPONSE';

// enroll upload

export const EN_SUBMIT_ENABLE_LOADER = 'EN_SUBMIT_ENABLE_LOADER';

export const EN_SUBMIT_DISABLE_LOADER = 'EN_SUBMIT_DISABLE_LOADER';

export const EN_SUBMIT_REQUEST = 'EN_SUBMIT_REQUEST';

export const EN_SUBMIT_RESPONSE = 'EN_SUBMIT_RESPONSE';

export const EN_SUBMIT_LOADING_ENDED = 'EN_SUBMIT_LOADING_ENDED';

export const EN_SUBMIT_FAILED = 'EN_SUBMIT_FAILED';

// enroll submit

export const EN_ENABLE_LOADER = 'EN_ENABLE_LOADER';

export const EN_DISABLE_LOADER = 'EN_DISABLE_LOADER';

export const EN_REQUEST = 'EN_REQUEST';

export const EN_RESPONSE = 'EN_RESPONSE';

export const EN_LOADING_ENDED = 'EN_LOADING_ENDED';

export const EN_FAILED = 'EN_FAILED';

//dashboard

export const DASHBOARD_ENABLE_LOADER = 'DASHBOARD_ENABLE_LOADER';

export const DASHBOARD_DISABLE_LOADER = 'DASHBOARD_DISABLE_LOADER';

export const DASHBOARD_REQUEST = 'DASHBOARD_REQUEST';

export const DASHBOARD_RESPONSE = 'DASHBOARD_RESPONSE';

export const DASHBOARD_FAILED = 'DASHBOARD_FAILED';

//services

export const SERVICES_ENABLE_LOADER = 'SERVICES_ENABLE_LOADER';
export const SERVICES_DISABLE_LOADER = 'SERVICES_DISABLE_LOADER';
export const SERVICES_REQUEST = 'SERVICES_REQUEST';
export const SERVICES_RESPONSE = 'SERVICES_RESPONSE';
export const SERVICES_FAILED = 'SERVICES_FAILED';

//news
export const NEWS_ENABLE_LOADER = 'NEWS_ENABLE_LOADER';

export const NEWS_DISABLE_LOADER = 'NEWS_DISABLE_LOADER';

export const NEWS_REQUEST = 'NEWS_REQUEST';

export const NEWS_RESPONSE = 'NEWS_RESPONSE';

export const NEWS_FAILED = 'NEWS_FAILED';

//terms

export const TERMS_ENABLE_LOADER = 'TERMS_ENABLE_LOADER';

export const TERMS_DISABLE_LOADER = 'TERMS_DISABLE_LOADER';

export const TERMS_REQUEST = 'TERMS_REQUEST';

export const TERMS_RESPONSE = 'TERMS_RESPONSE';

export const TERMS_FAILED = 'TERMS_FAILED';

//help

export const HELP_ENABLE_LOADER = 'HELP_ENABLE_LOADER';

export const HELP_DISABLE_LOADER = 'HELP_DISABLE_LOADER';

export const HELP_REQUEST = 'HELP_REQUEST';

export const HELP_RESPONSE = 'HELP_RESPONSE';

export const HELP_FAILED = 'HELP_FAILED';

//privacy

export const PRIVACY_ENABLE_LOADER = 'PRIVACY_ENABLE_LOADER';

export const PRIVACY_DISABLE_LOADER = 'PRIVACY_DISABLE_LOADER';

export const PRIVACY_REQUEST = 'PRIVACY_REQUEST';

export const PRIVACY_RESPONSE = 'PRIVACY_RESPONSE';

export const PRIVACY_FAILED = 'PRIVACY_FAILED';

//logout

export const LOGOUT_ENABLE_LOADER = 'LOGOUT_ENABLE_LOADER';

export const LOGOUT_DISABLE_LOADER = 'LOGOUT_DISABLE_LOADER';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';

export const LOGOUT_RESPONSE = 'LOGOUT_RESPONSE';

export const LOGOUT_FAILED = 'LOGOUT_FAILED';


// Country
export const COUNTRY_ENABLE_LOADER = 'COUNTRY_ENABLE_LOADER';
export const COUNTRY_DISABLE_LOADER = 'COUNTRY_DISABLE_LOADER';
export const COUNTRY_REQUEST = 'COUNTRY_REQUEST';
export const COUNTRY_RESPONSE = 'COUNTRY_RESPONSE';
export const COUNTRY_FAILED = 'COUNTRY_FAILED';
